export interface GanttTask {
    id: string;
    stage: string;
    assignee: string;
    avatarUrl: string | null;
    title: string;
    startDate: string;
    endDate: string;
}

export const ganttData: GanttTask[] = [
  {
    id: "task-001",
    stage: "ПІДГОТОВКА",
    assignee: "Максим С.",
    avatarUrl: "./avatars/maksym.jpg",
    title: "Барна стійка",
    startDate: "2026-04-02",
    endDate: "2026-04-10",
  },
  {
    id: "task-002",
    stage: "ПІДГОТОВКА",
    assignee: "Максим С.",
    avatarUrl: "./avatars/maksym.jpg",
    title: "Лавка",
    startDate: "2026-04-08",
    endDate: "2026-04-14",
  },
  {
    id: "task-003",
    stage: "ПІДГОТОВКА",
    assignee: "Олена К.",
    avatarUrl: "./avatars/olena.jpg",
    title: "Шафа у спальню",
    startDate: "2026-04-05",
    endDate: "2026-04-18",
  },
  {
    id: "task-004",
    stage: "ПІДГОТОВКА",
    assignee: "Без відповідального",
    avatarUrl: null,
    title: "Кухня",
    startDate: "2026-04-12",
    endDate: "2026-04-28",
  },
  {
    id: "task-005",
    stage: "ПІДГОТОВКА",
    assignee: "Ірина М.",
    avatarUrl: "./avatars/iryna.jpg",
    title: "Тумба під ТВ",
    startDate: "2026-04-20",
    endDate: "2026-04-31",
  },
  {
    id: "task-006",
    stage: "ВИРОБНИЦТВО",
    assignee: "Андрій П.",
    avatarUrl: "./avatars/andrii.jpg",
    title: "Корпус кухні",
    startDate: "2026-04-16",
    endDate: "2026-05-04",
  },
  {
    id: "task-007",
    stage: "ВИРОБНИЦТВО",
    assignee: "Андрій П.",
    avatarUrl: "./avatars/andrii.jpg",
    title: "Фасади кухні",
    startDate: "2026-04-25",
    endDate: "2026-05-12",
  },
  {
    id: "task-008",
    stage: "ВИРОБНИЦТВО",
    assignee: "Сергій Д.",
    avatarUrl: "./avatars/serhii.jpg",
    title: "Стільниця",
    startDate: "2026-05-01",
    endDate: "2026-05-08",
  },
  {
    id: "task-009",
    stage: "ВИРОБНИЦТВО",
    assignee: "Сергій Д.",
    avatarUrl: "./avatars/serhii.jpg",
    title: "Шухляди",
    startDate: "2026-05-06",
    endDate: "2026-05-17",
  },
  {
    id: "task-010",
    stage: "ВИРОБНИЦТВО",
    assignee: "Без відповідального",
    avatarUrl: null,
    title: "Полиці",
    startDate: "2026-05-10",
    endDate: "2026-05-20",
  },
  {
    id: "task-011",
    stage: "КОМПЛЕКТУВАННЯ",
    assignee: "Наталія Р.",
    avatarUrl: "./avatars/nataliia.jpg",
    title: "Фурнітура для кухні",
    startDate: "2026-04-10",
    endDate: "2026-04-22",
  },
  {
    id: "task-012",
    stage: "КОМПЛЕКТУВАННЯ",
    assignee: "Наталія Р.",
    avatarUrl: "./avatars/nataliia.jpg",
    title: "Петлі та направляючі",
    startDate: "2026-04-18",
    endDate: "2026-04-29",
  },
  {
    id: "task-013",
    stage: "КОМПЛЕКТУВАННЯ",
    assignee: "Олег В.",
    avatarUrl: "./avatars/oleh.jpg",
    title: "Матеріали для шафи",
    startDate: "2026-04-24",
    endDate: "2026-05-05",
  },
  {
    id: "task-014",
    stage: "КОМПЛЕКТУВАННЯ",
    assignee: "Олег В.",
    avatarUrl: "./avatars/oleh.jpg",
    title: "Замовлення ДСП",
    startDate: "2026-05-02",
    endDate: "2026-05-15",
  },
  {
    id: "task-015",
    stage: "КОМПЛЕКТУВАННЯ",
    assignee: "Без відповідального",
    avatarUrl: null,
    title: "Комплект ручок",
    startDate: "2026-05-12",
    endDate: "2026-05-22",
  },
  {
    id: "task-016",
    stage: "МОНТАЖ",
    assignee: "Роман Л.",
    avatarUrl: "./avatars/roman.jpg",
    title: "Монтаж барної стійки",
    startDate: "2026-05-06",
    endDate: "2026-05-09",
  },
  {
    id: "task-017",
    stage: "МОНТАЖ",
    assignee: "Роман Л.",
    avatarUrl: "./avatars/roman.jpg",
    title: "Монтаж кухні",
    startDate: "2026-05-15",
    endDate: "2026-05-25",
  },
  {
    id: "task-018",
    stage: "МОНТАЖ",
    assignee: "Віктор Н.",
    avatarUrl: "./avatars/viktor.jpg",
    title: "Монтаж шафи",
    startDate: "2026-05-20",
    endDate: "2026-05-28",
  },
  {
    id: "task-019",
    stage: "МОНТАЖ",
    assignee: "Віктор Н.",
    avatarUrl: "./avatars/viktor.jpg",
    title: "Регулювання фасадів",
    startDate: "2026-05-27",
    endDate: "2026-05-30",
  },
  {
    id: "task-020",
    stage: "МОНТАЖ",
    assignee: "Без відповідального",
    avatarUrl: null,
    title: "Фінальна перевірка",
    startDate: "2026-05-29",
    endDate: "2026-06-01",
  }
];